function Stop_L2 () {
    pins.digitalWritePin(DigitalPin.P1, 0)
}
function Left () {
    pins.digitalWritePin(DigitalPin.P0, 1)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P8, 0)
    pins.digitalWritePin(DigitalPin.P12, 1)
}
input.onButtonPressed(Button.A, function () {
    Call_Forward()
    basic.pause(1200)
    Stop()
    basic.pause(100)
    Turn_l()
    basic.pause(700)
    Stop_L2()
    basic.pause(100)
    Call_Forward()
    basic.pause(2500)
    Stop()
    basic.pause(100)
    Turn_r2()
    basic.pause(500)
    Stop_R()
    basic.pause(100)
    Call_Forward()
    basic.pause(500)
    Stop()
    basic.pause(100)
    Turn_r2()
    basic.pause(950)
    Stop_R()
    basic.pause(100)
    Call_Forward()
    basic.pause(3800)
    Stop()
    basic.pause(100)
    Turn_r2()
    basic.pause(800)
    Stop_R()
    basic.pause(100)
    Call_Forward()
    basic.pause(1300)
    Stop()
    basic.pause(100)
    Turn_l()
    basic.pause(950)
    Stop_L2()
    basic.pause(100)
    Call_Forward()
    basic.pause(2000)
    Stop()
})
function Call_Forward () {
    pins.digitalWritePin(DigitalPin.P0, 1)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P8, 1)
    pins.digitalWritePin(DigitalPin.P12, 0)
}
function Turn_r2 () {
    pins.digitalWritePin(DigitalPin.P8, 1)
}
input.onButtonPressed(Button.B, function () {
    Call_Forward()
    basic.pause(2000)
    Stop()
    basic.pause(100)
    Left()
    basic.pause(500)
    Stop_L2()
    basic.pause(100)
    Call_Forward()
    basic.pause(2000)
    Stop()
    basic.pause(100)
    Left()
    basic.pause(500)
    Stop_L2()
    basic.pause(100)
    Call_Forward()
    basic.pause(2000)
    Stop()
    basic.pause(100)
    Left()
    basic.pause(500)
    Stop_L2()
    basic.pause(100)
    Call_Forward()
    basic.pause(2000)
    Stop()
})
function Stop_R () {
    pins.digitalWritePin(DigitalPin.P8, 0)
}
function Right () {
    pins.digitalWritePin(DigitalPin.P0, 0)
    pins.digitalWritePin(DigitalPin.P1, 1)
    pins.digitalWritePin(DigitalPin.P8, 1)
    pins.digitalWritePin(DigitalPin.P12, 0)
}
function Turn_l () {
    pins.digitalWritePin(DigitalPin.P1, 1)
}
function Stop () {
    pins.digitalWritePin(DigitalPin.P0, 0)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P8, 0)
    pins.digitalWritePin(DigitalPin.P12, 0)
}
function Backward () {
    pins.digitalWritePin(DigitalPin.P0, 0)
    pins.digitalWritePin(DigitalPin.P1, 1)
    pins.digitalWritePin(DigitalPin.P8, 0)
    pins.digitalWritePin(DigitalPin.P12, 1)
}
